### ISSUE TITLE
AnimationController.dispose() called more than once

### ISSUE THREAD

**Issue by JagandeepBrar** [aagarwal1012/Animated-Text-Kit#58]
**Describe the bug**
When using `TyperAnimatedTextKit` in a widget that will eventually get removed, an error is shown because the animation controller is attempted to be destroyed multiple times.

**To Reproduce**
In my use case, I have a FutureBuilder that calls a "Loading" widget (Which contains a `TyperAnimatedTextKit`), and once the data is loaded FutureBuilder removes the loading widget and replaces it with the content widgets.

**Expected behavior**
It still works, and it doesn't cause a crash but it prints out to the command line each time (as well as logs internally in my logger).

**Screenshots**

```
AnimationController#54de2(⏭ 1.000; paused; DISPOSED)] [Exception: AnimationController.dispose() called more than once.
A given AnimationController cannot be disposed more than once.
The following AnimationController object was disposed multiple times:
  AnimationController#54de2(⏭ 1.000; paused; DISPOSED)] [LogLevel.FATAL] [March 08, 2020 - 06:31:29 PM] [#0      AnimationController.dispose.<anonymous closure> 
package:flutter/…/animation/animation_controller.dart:751
#1      AnimationController.dispose 
package:flutter/…/animation/animation_controller.dart:762
#2      _TyperState._nextAnimation 
package:animated_text_kit/src/typer.dart:190
#3      _rootRun  (dart:async/zone.dart:1122:38)
#4      _CustomZone.run  (dart:async/zone.dart:1023:19)
#5      _CustomZone.runGuarded  (dart:async/zone.dart:925:7)
#6      _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:965:23)
#7      _rootRun  (dart:async/zone.dart:1126:13)
#8      _CustomZone.run  (dart:async/zone.dart:1023:19)
#9      _CustomZone.bindCallback.<anonymous closure>  (dart:async/zone.dart:949:23)
#10     Timer._createTimer.<anonymous closure>  (dart:async-patch/timer_patch.dart:23:15)
#11     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:384:19)
#12     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:418:5)
#13     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:174:12)
]
```

**Flutter:**
 - v1.12.13+hotfix.8
 - Stable

**Dart:**
 - 2.7.0

**Comment by awhitford** [comment]
I am seeing a similar issue with a single `FadeAnimatedTextKit`:
```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: AnimationController.dispose() called more than once.
A given AnimationController cannot be disposed more than once.
The following AnimationController object was disposed multiple times:
  AnimationController#88138(⏭ 1.000; paused; DISPOSED)
#0      AnimationController.dispose.<anonymous closure> (package:flutter/src/animation/animation_controller.dart:751:9)
#1      AnimationController.dispose (package:flutter/src/animation/animation_controller.dart:762:6)
#2      _RotatingTextState._nextAnimation (package:animated_text_kit/src/fade.dart:207:42)
#3      _rootRun (dart:async/zone.dart:1122:38)
#4      _CustomZone.run (dart:async/zone.dart:1023:19)
#5      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#7      _rootRun (dart:async/zone.dart:1126:13)
#8      _CustomZone.run (dart:async/zone.dart:1023:19)
#9      _CustomZone.bindCallback.<anonymous closur<…>
```

**Comment by awhitford** [comment]
The problem appears during a screen transition, so the widget's `dispose` is conflicting with [this code in `nextAnimation`](https://github.com/aagarwal1012/Animated-Text-Kit/blob/master/lib/src/fade.dart#L207):
```dart
    if (_controller != null) _controller.dispose();

    setState(() {});

    _controller = new AnimationController(
      duration: _duration,
      vsync: this,
    );
```

I recommend refactoring such that the lifecycle of the `AnimationController` is closely linked to the widget lifecycle.  In other words, I would avoid replacing it during `nextAnimation` -- instead, just reset it or something.

Of course, the simplest solution may be simply to null it after you dispose it.  So, replace:
```dart
    if (_controller != null) _controller.dispose();
```
with 
```dart
    _controller?.dispose();
    _controller = null;
```

Then, you will need to add a guard to the widget's [dispose method](https://github.com/aagarwal1012/Animated-Text-Kit/blob/master/lib/src/fade.dart#L150) too:
```dart
   if (null != _controller) {
    _controller
      ..stop()
      ..dispose();
    }
```

**Comment by Skyost** [comment]
I have the same error :

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: AnimationController.dispose() called more than once.
A given AnimationController cannot be disposed more than once.
The following AnimationController object was disposed multiple times:
  AnimationController#21ba7(⏭ 1.000; paused; DISPOSED)
#0      AnimationController.dispose.<anonymous closure> (package:flutter/src/animation/animation_controller.dart:751:9)
#1      AnimationController.dispose (package:flutter/src/animation/animation_controller.dart:762:6)
#2      _TyperState._nextAnimation (package:animated_text_kit/src/typer.dart:190:42)
#3      _rootRun (dart:async/zone.dart:1122:38)
#4      _CustomZone.run (dart:async/zone.dart:1023:19)
#5      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#7      _rootRun (dart:async/zone.dart:1126:13)
#8      _CustomZone.run (dart:async/zone.dart:1023:19)
#9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by aadarshadhakalg** [comment]
Beside of the TyperAnimatedTextKit widget, have you used any other animation ? I mean have you created your custom animation controller in same file?

**Comment by yiminghan** [comment]
I'm getting into the same issue. I agree with @awhitford we should just set the controller to null after dispose.

**Comment by aagarwal1012** [comment]
**v2.1.0** of Animated text kit solves this issue, closing this issue for now. Feel free to reopen this issue if any issue arises.

**Comment by awhitford** [comment]
Code like [this](https://github.com/aagarwal1012/Animated-Text-Kit/commit/13da3802357365f5ee57ac92b8e68d7e92746fb5#diff-2c3c0cfccb5fd886846ed3520d7b3880R158):
```dart
_controller?.stop();
_controller.dispose();
```
is a problem and it isn't any better than:
```dart
_controller
  ..stop()
  ..dispose();
```

If `_controller` is null, then the `?.` will protect `stop()`, but then you will get a _Null Pointer Exception_ calling `dispose()`.

Some are fine (rotate, scale), but some are faulty (colorize, fade).

Also, this code:
```dart
if (_controller != null) {	    
  _controller
    ..stop()
    ..dispose();
}
```
 is logically the same:
```dart
_controller?.stop();
_controller?.dispose();
```
The latter is more concise, but arguably less efficient (unless the optimizer can optimize the double `?.`).

**Comment by niumj** [comment]
May be you wrote the source [_controller.dispose();] in the method build.
But Flutter would call build multiple times.So you try to write the code [_controller.dispose();]  in the method dispose etc.
